services:
  find-event:
    image: postgis/postgis:15-3.5
    restart: unless-stopped
    ports:
      - '5436:5432'
    environment:
      POSTGRES_DB: find-event
      POSTGRES_PASSWORD: find-event-pwd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - find-event-db-vol:/var/lib/postgresql/data

  redis:
    image: redis:7.4.4
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ["redis-server", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - redis-data:/data

volumes:
  find-event-db-vol:
    driver: local
  redis-data:
    driver: local