version: '3.9'

services:
  # WMS DB
  find-event:
    image: postgres:15.2
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: find-event
      POSTGRES_PASSWORD: find-event-pwd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - find-event-db-vol:/var/lib/postgresql/data

volumes:
  find-event-db-vol:
    driver: local