version: '3.9'

services:
  find-event:
    image: postgis/postgis:15-3.5
    restart: unless-stopped
    ports:
      - '5436:5432'
    environment:
      POSTGRES_DB: find-event
      POSTGRES_PASSWORD: find-event-pwd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - find-event-db-vol:/var/lib/postgresql/data

volumes:
  find-event-db-vol:
    driver: local