server:
  port: 8082
  servlet:
    context-path: /api

spring:
  flyway:
    find-event:
      locations: classpath:db.migration
    enabled: true
    baseline-on-migrate: true

  redis:
    host: localhost
    port: 6379
    cache:
      type: redis

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/find-event?currentSchema=public
    username: find-event-admin
    password: find-event-pwd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: no
        show_sql: true
        jdbc:
          batch_size: 200
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

jwt:
  secret: uY7$eL!9kP#sR3qZ@2vNfX!tD8^zKwL%gE1bJ0mH
  expiration: 86400
